# Code Coverage: see https://docs.codecov.io/v5.0.0/docs/codecov-yaml

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
      project:
        default: on
      patch:
        default: on
      changes:
        default: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
