language: android

jdk: oraclejdk8

sudo: required

env:
  global:
   - ANDROID_API_LEVEL=28
   - ANDROID_BUILD_TOOLS_VERSION=28.0.0
   - ANDROID_EMU_API_LEVEL=24
   - ANDROID_ABI=armeabi-v7a

before_install:
  - yes | sdkmanager "platforms;android-26"

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

licenses:
  - '.+'

before_script:
  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - ./gradlew connectedCheck
  - adb shell input keyevent 82 &

script:
  - ./gradlew build createMockDebugCoverageReport jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
